* clean up  * checks if the directory is already a working copy, and if it    is not a WC from another repository than the intended one.    In that case, it only tries to add the files and set the properties.  * more 'set -e' friendly (previous version was failing when set -e was used)
git-svn-id: svn+ssh://svn.laas.fr/svn/jafar/jafarBackbone/trunk@1272 d3dd4ecc-a6df-0310-ac42-d4bc92953605

diff --git a/bin/svn-add-module b/bin/svn-add-module
--- a/bin/svn-add-module
+++ b/bin/svn-add-module
@@ -1,55 +1,105 @@
-#!/bin/sh
+#! /bin/sh
 
 # $Id$ #
 set -e
 
-mv $1 ${1}_tmp
-svn mkdir -m"new module !" svn+ssh://$USER@pollux.laas.fr/svn/jafar/jafarModules/trunk/${1}
-svn co svn+ssh://$USER@pollux.laas.fr/svn/jafar/jafarModules/trunk/${1} $1
-mv ${1}_tmp/* $1
-rm -rf ${1}_tmp
+usage()
+{
+    cat <<EOF
+svn-add-module name [repository]
+    imports the jafar module 'name' at the given SVN URL
 
-cd $1
-svn add -N COPYRIGHT Makefile README User.make doc include macro src test_suite
-svn ps svn:keywords Id COPYRIGHT Makefile README User.make
-cd doc/
-svn add *.doxy 
-svn add *.tcl 
-svn add *.hpp 
-svn add *.tpp 
-svn add *.cpp 
-svn ps svn:keywords Id *.doxy 
-svn ps svn:keywords Id *.tcl 
-svn ps svn:keywords Id *.hpp 
-svn ps svn:keywords Id *.tpp 
-svn ps svn:keywords Id *.cpp
-cd ../include
-svn add *.i
-svn ps svn:keywords Id *.i
-svn add -N $1
-cd $1
-svn add *.hpp 
-svn add *.tpp 
-svn add *.h 
-svn add *.i
-svn ps svn:keywords Id *.hpp 
-svn ps svn:keywords Id *.tpp 
-svn ps svn:keywords Id *.h 
-svn ps svn:keywords Id *.i
-cd ../../macro
-svn add *.tcl
-svn add *.rb
-svn ps svn:keywords Id *.tcl *.rb
-cd ../src
-svn add *.cpp 
-svn add *.c
-svn ps svn:keywords Id *.cpp 
-svn ps svn:keywords Id *.c
-svn propset svn:ignore 'kernel_wrap.cpp' ruby/
-cd ../test_suite
-svn add *.cpp
-svn ps svn:keywords Id *.cpp
-svn add *.hpp
-svn ps svn:keywords Id *.hpp
+The script adds C, C++, Swig and scripts and sets the needed svn properties. 
+You have to add any other files (if any) manually
+EOF
+    exit 1
+}
 
-echo "\nDo not forget to commit these changes !"
+MODULE=$1
+test -z "$MODULE" && usage;
+
+if ! test -d "$MODULE"; then
+    echo "ERROR: $MODULE is not a directory"
+    exit 1
+fi
+
+URL=$2
+if test -z "$URL"; then
+    URL="svn+ssh://$USER@pollux.laas.fr/svn/jafar/jafarModules"
+    cat <<EOF
+WARNING: No repository URL given on command line, will use
+WARNING: ${URL}
+EOF
+fi
+URL=${URL}/${MODULE}
+
+# Check if the module directory is already a svn checkout
+# Note: svn info does not fail (i.e. returns a non-zero status code)
+# if the directory exists but is not a svn working copy
+url=`svn info $MODULE | grep URL | sed 's/URL: //'`
+
+if test -n "$url"; then
+    if test "$url" != "$URL"; then
+        echo "$MODULE/ is already a svn working copy, but the repository URLs differ."
+        echo "I'm trying to add the module in $URL while the working copy is in $url"
+        exit 1
+    fi
+    echo "$MODULE/ is already a working copy, I will only set the files up"
+else
+    # Adds an empty module directory in the repository, checks it out
+    # and move all files into the new directory
+    # The non-svn directory is renamed to ${MODULE}_bak
+    svn mkdir -m "new module $MODULE" $URL
+    svn co $URL ${MODULE}_tmp
+    cp -a ${MODULE}/* ${MODULE}_tmp
+    mv ${MODULE} ${MODULE}_bak
+    mv ${MODULE}_tmp ${MODULE}
+fi
+
+TOPDIR=$PWD/$MODULE
+
+svn_add() {
+    for file in "$@"; do
+        if test -d "$file"; then
+            svn add -N "$file"
+        elif test -f "$file"; then
+            svn add "$file"
+            svn ps svn:keywords Id "$file"
+        fi
+
+        # Skip unexistant files since we are using wildcards
+    done
+}
+
+cd $TOPDIR
+svn_add COPYRIGHT Makefile README User.make doc include macro src test_suite
+
+cd $TOPDIR/doc
+svn_add *.doxy *.tcl *.hpp *.tpp *.cpp
+
+cd $TOPDIR/include
+svn_add $MODULE *.i
+
+cd $TOPDIR/include/$MODULE
+svn_add *.hpp *.tpp *.h *.i
+
+cd $TOPDIR/macro
+svn_add *.tcl *.rb
+
+cd $TOPDIR/src
+svn_add *.cpp *.c ruby
+
+cd $TOPDIR/src/ruby
+svn_add extconf.rb
+svn propset svn:ignore 'kernel_wrap.cpp' .
+
+cd $TOPDIR/test_suite
+svn_add *.cpp *.hpp
+
+cat <<EOF
+
+*** 
+*** Do not forget to commit these changes !
+***
+EOF
+
