add info for camera module
git-svn-id: svn+ssh://svn.laas.fr/svn/jafar/jafarBackbone/trunk@1006 d3dd4ecc-a6df-0310-ac42-d4bc92953605

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -465,7 +465,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LN_S EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SHLIB_SUFFIX SWIG SWIG_RUNTIME_LIBS_DIR TCL_CPPFLAGS TCL_EXTRA_CFLAGS TCL_SHLIB_SUFFIX TCL_CC LIB_RUNTIME_DIR TCL_LDFLAGS TCL_LIB_SPEC TK_LIB_SPEC TCL_SHLIB_LDFLAGS TCL_SHLIB_CFLAGS TCL_SHLIB_LD TCL_LIB_FLAGS BOOST_CPPFLAGS BOOST_LDFLAGS OPENCV_CPPFLAGS OPENCV_LDFLAGS BOOST_SANDBOX_CPPFLAGS LAPACK_LDFLAGS OPENGL_CPPFLAGS OPENGL_LDFLAGS IEEE1394_CPPFLAGS IEEE1394_LDFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LN_S EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SHLIB_SUFFIX SWIG SWIG_RUNTIME_LIBS_DIR TCL_CPPFLAGS TCL_EXTRA_CFLAGS TCL_SHLIB_SUFFIX TCL_CC LIB_RUNTIME_DIR TCL_LDFLAGS TCL_LIB_SPEC TK_LIB_SPEC TCL_SHLIB_LDFLAGS TCL_SHLIB_CFLAGS TCL_SHLIB_LD TCL_LIB_FLAGS BOOST_CPPFLAGS BOOST_LDFLAGS OPENCV_CPPFLAGS OPENCV_LDFLAGS BOOST_SANDBOX_CPPFLAGS LAPACK_LDFLAGS OPENGL_CPPFLAGS OPENGL_LDFLAGS IEEE1394_CPPFLAGS IEEE1394_LDFLAGS QUICKTIME_LDFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1157,7 +1157,7 @@ Optional Packages:
   --without-v4l
 
   --with-v4linc=dir
-      support for v4l. default: --with-v4l
+      support for v4l (only available on Linux). default: --with-v4l
       if --with-v4l or --with-v4l=yes is given: v4l package files will be
          searched for in some standard directories (the default).
       if --with-v4l=dir is given, and dir is a directory: v4l package files
@@ -1166,6 +1166,21 @@ Optional Packages:
          not be used.
       alternatively, you can specify:
         --with-v4linc=dir : the v4l package's include directory
+
+  --with-quicktime
+  --with-quicktime=dir
+  --without-quicktime
+
+  --with-quicktimeinc=dir
+      support for QuickTime (only available on MacOSX). default: --with-quicktime
+      if --with-quicktime or --with-quicktime=yes is given: quicktime package files will be
+         searched for in some standard directories (the default).
+      if --with-quicktime=dir is given, and dir is a directory: quicktime package files
+         will be searched for below 'dir' using 'find'.
+      if --with-quicktime=no or --without-quicktime is given: quicktime package will
+         not be used.
+      alternatively, you can specify:
+        --with-quicktimeinc=dir : the quicktime package's include directory
   --with-includes=DIR     search include DIR for optional packages below
   --with-libraries=DIR    search library DIR for optional packages below
 
@@ -3599,7 +3614,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3602 "configure"' > conftest.$ac_ext
+  echo '#line 3617 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4707,7 +4722,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4710:" \
+echo "$as_me:4725:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5741,11 +5756,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5744: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5759: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5748: \$? = $ac_status" >&5
+   echo "$as_me:5763: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -5973,11 +5988,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5976: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5991: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5980: \$? = $ac_status" >&5
+   echo "$as_me:5995: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6040,11 +6055,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6043: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6058: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6047: \$? = $ac_status" >&5
+   echo "$as_me:6062: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8172,7 +8187,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8175 "configure"
+#line 8190 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8270,7 +8285,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8273 "configure"
+#line 8288 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10457,11 +10472,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10460: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10475: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10464: \$? = $ac_status" >&5
+   echo "$as_me:10479: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10524,11 +10539,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10527: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10542: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10531: \$? = $ac_status" >&5
+   echo "$as_me:10546: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11853,7 +11868,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11856 "configure"
+#line 11871 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11951,7 +11966,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11954 "configure"
+#line 11969 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12776,11 +12791,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12779: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12794: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12783: \$? = $ac_status" >&5
+   echo "$as_me:12798: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12843,11 +12858,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12846: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12861: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12850: \$? = $ac_status" >&5
+   echo "$as_me:12865: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14826,11 +14841,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14829: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14844: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14833: \$? = $ac_status" >&5
+   echo "$as_me:14848: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15058,11 +15073,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15061: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15076: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15065: \$? = $ac_status" >&5
+   echo "$as_me:15080: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15125,11 +15140,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15128: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15143: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15132: \$? = $ac_status" >&5
+   echo "$as_me:15147: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17257,7 +17272,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17260 "configure"
+#line 17275 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17355,7 +17370,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17358 "configure"
+#line 17373 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21200,6 +21215,192 @@ _ACEOF
 
 fi
 
+## check for quicktime
+
+
+# Check whether --with-quicktime or --without-quicktime was given.
+if test "${with_quicktime+set}" = set; then
+  withval="$with_quicktime"
+
+fi;
+
+
+# Check whether --with-quicktimeinc or --without-quicktimeinc was given.
+if test "${with_quicktimeinc+set}" = set; then
+  withval="$with_quicktimeinc"
+
+fi;
+
+
+    # default is "no"
+    if test ${with_quicktime:-""} = ""; then
+        with_quicktime="no"
+    fi
+
+    if test ${with_quicktime:-""} != "no"; then
+	found_quicktime="yes"
+
+
+    if test "QuickTime/QuickTime.h" != ""; then
+        echo "$as_me:$LINENO: checking for QuickTime/QuickTime.h " >&5
+echo $ECHO_N "checking for QuickTime/QuickTime.h ... $ECHO_C" >&6
+
+        # check whether the include is in the path by default (e.g. /usr/include)
+        include_found=""
+        if test "$with_quicktimeinc" = "" -a "$with_quicktime" = "yes"; then
+            cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdio.h>  /* necessary because jpeglib.h fails to include it */
+#include <QuickTime/QuickTime.h>
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  include_found="in default path"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+include_found=""
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+        fi
+
+        # if not found by default, try searching for it
+        if test "$include_found" = ""; then
+            dirs=""
+            if test "$with_quicktimeinc" != ""; then
+                dirs="$with_quicktimeinc"
+            elif test "$with_quicktime" != "yes"; then
+                dirs="$with_quicktime"
+            else
+                dirs="/usr/local/include /usr/local/gnu/include /usr/local/quicktime /usr/local/quicktime/include /opt/include /opt/gnu/include /opt/quicktime /opt/quicktime/include /opt/local/include /opt/local/include/quicktime /usr/include /sw /sw/include /sw/quicktime /sw/quicktime/include \$HOME/ \$HOME/include \$HOME/usr \$HOME/usr/include \$HOME/usr/quicktime \$HOME/opt \$HOME/opt/include \$HOME/opt/quicktime \$HOME/quicktime \$HOME/local \$HOME/local/include \$HOME/local/quicktime"
+            fi
+
+            # use find for searching
+
+    if test "$findprog" = ""; then
+        if test "$CYGWIN" = "yes"; then
+          findprog="/usr/bin/find"
+        else
+          findprog="find"
+        fi
+    fi
+
+
+            # first, look for the given header file without directory components..
+            found=""
+            for i in $dirs; do
+                if test -d $i; then
+                    found="$found `$findprog $i -follow -name QuickTime.h -print 2> /dev/null`"
+                fi
+            done
+
+            # now, check each found file for relative path prefix.
+
+    regExResult=""
+    if test "$found" != ""; then
+        for i in $found; do
+            regExResult=`expr "$i" : "\(.*include\)/QuickTime/QuickTime\.h"`
+            if test "$regExResult" != ""; then
+                break
+            fi
+        done
+    fi
+
+            if test "$regExResult" = ""; then
+
+    regExResult=""
+    if test "$found" != ""; then
+        for i in $found; do
+            regExResult=`expr "$i" : "\(.*\)/QuickTime/QuickTime\.h"`
+            if test "$regExResult" != ""; then
+                break
+            fi
+        done
+    fi
+
+            fi
+            include_found=$regExResult
+        fi
+
+        # report the search result and set result variables
+        if test "$include_found" = ""; then
+            with_quicktimeinc=""
+            echo "$as_me:$LINENO: result: not found in $dirs" >&5
+echo "${ECHO_T}not found in $dirs" >&6
+        else
+            echo "$as_me:$LINENO: result: $include_found" >&5
+echo "${ECHO_T}$include_found" >&6
+            if test "$include_found" != "/usr/include" -a \
+                    "$include_found" != "in default path"; then
+                with_quicktimeinc="$include_found"
+                quicktime_cppflags="-I$include_found"
+            else
+                with_quicktimeinc=""
+                quicktime_cppflags=""
+            fi
+        fi
+    else
+        with_quicktimeinc=""
+        quicktime_cppflags=""
+    fi
+
+	 	if test "x$include_found" = "x"; then
+			found_quicktime="no"
+        	fi
+
+
+
+	with_quicktime="yes";
+    else
+	with_quicktime="no"
+	{ echo "$as_me:$LINENO: WARNING: Configuring without quicktime support " >&5
+echo "$as_me: WARNING: Configuring without quicktime support " >&2;}
+    fi
+
+
+if test "x$with_quicktime" = "xyes";
+then
+    QUICKTIME_LDFLAGS="-Wl,-framework -Wl,Carbon -Wl,-framework -Wl,Quicktime"
+
+    cat >>confdefs.h <<\_ACEOF
+#define HAVE_QUICKTIME 1
+_ACEOF
+
+fi
+
 ##########################
 # Check for header files #
 ##########################
@@ -22174,6 +22375,7 @@ s,@OPENGL_CPPFLAGS@,$OPENGL_CPPFLAGS,;t t
 s,@OPENGL_LDFLAGS@,$OPENGL_LDFLAGS,;t t
 s,@IEEE1394_CPPFLAGS@,$IEEE1394_CPPFLAGS,;t t
 s,@IEEE1394_LDFLAGS@,$IEEE1394_LDFLAGS,;t t
+s,@QUICKTIME_LDFLAGS@,$QUICKTIME_LDFLAGS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
