detect the calife's libstereopixel
git-svn-id: svn+ssh://svn.laas.fr/svn/jafar/jafarBackbone/trunk@2484 d3dd4ecc-a6df-0310-ac42-d4bc92953605

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -865,6 +865,9 @@ QT4_LDFLAGS
 CALIFECAMERA_CPPFLAGS
 CALIFECAMERA_LIBS
 CALIFECAMERA_LDFLAGS
+STEREOPIXEL_CPPFLAGS
+STEREOPIXEL_LIBS
+STEREOPIXEL_LDFLAGS
 BOOST_SANDBOX_CPPFLAGS
 LAPACK_LDFLAGS
 LAPACK_LIBS
@@ -4434,7 +4437,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4437 "configure"' > conftest.$ac_ext
+  echo '#line 4440 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6801,11 +6804,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6804: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6807: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6808: \$? = $ac_status" >&5
+   echo "$as_me:6811: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7033,11 +7036,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7036: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7039: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7040: \$? = $ac_status" >&5
+   echo "$as_me:7043: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7100,11 +7103,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7103: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7106: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7107: \$? = $ac_status" >&5
+   echo "$as_me:7110: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9339,7 +9342,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9342 "configure"
+#line 9345 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9437,7 +9440,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9440 "configure"
+#line 9443 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11652,11 +11655,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11655: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11658: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11659: \$? = $ac_status" >&5
+   echo "$as_me:11662: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11719,11 +11722,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11722: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11725: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11726: \$? = $ac_status" >&5
+   echo "$as_me:11729: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13127,7 +13130,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13130 "configure"
+#line 13133 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13225,7 +13228,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13228 "configure"
+#line 13231 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14050,11 +14053,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14053: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14056: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14057: \$? = $ac_status" >&5
+   echo "$as_me:14060: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14117,11 +14120,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14120: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14123: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14124: \$? = $ac_status" >&5
+   echo "$as_me:14127: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16127,11 +16130,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16130: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16133: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16134: \$? = $ac_status" >&5
+   echo "$as_me:16137: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16359,11 +16362,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16362: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16365: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16366: \$? = $ac_status" >&5
+   echo "$as_me:16369: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16426,11 +16429,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16429: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16432: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16433: \$? = $ac_status" >&5
+   echo "$as_me:16436: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18665,7 +18668,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18668 "configure"
+#line 18671 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18763,7 +18766,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18766 "configure"
+#line 18769 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21867,6 +21870,118 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
     AVAIL_EXTLIBS="califecamera $AVAIL_EXTLIBS"
+fi
+
+## check for libstereopixel ##
+
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        { echo "$as_me:$LINENO: checking for calife-stereopixel >= 0.1" >&5
+echo $ECHO_N "checking for calife-stereopixel >= 0.1... $ECHO_C" >&6; }
+
+        if $PKG_CONFIG --exists "calife-stereopixel >= 0.1" ; then
+            { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+            succeeded=yes
+
+            { echo "$as_me:$LINENO: checking STEREOPIXEL_CPPFLAGS" >&5
+echo $ECHO_N "checking STEREOPIXEL_CPPFLAGS... $ECHO_C" >&6; }
+            STEREOPIXEL_CPPFLAGS=`$PKG_CONFIG --cflags "calife-stereopixel >= 0.1"`
+            { echo "$as_me:$LINENO: result: $STEREOPIXEL_CPPFLAGS" >&5
+echo "${ECHO_T}$STEREOPIXEL_CPPFLAGS" >&6; }
+
+            { echo "$as_me:$LINENO: checking STEREOPIXEL_LIBS" >&5
+echo $ECHO_N "checking STEREOPIXEL_LIBS... $ECHO_C" >&6; }
+            STEREOPIXEL_LIBS=`$PKG_CONFIG --libs "calife-stereopixel >= 0.1"`
+            { echo "$as_me:$LINENO: result: $STEREOPIXEL_LIBS" >&5
+echo "${ECHO_T}$STEREOPIXEL_LIBS" >&6; }
+        else
+            STEREOPIXEL_CPPFLAGS=""
+            STEREOPIXEL_LIBS=""
+## If we have a custom action on failure, don't print errors, but
+## do set a variable so people can do so.
+            STEREOPIXEL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "calife-stereopixel >= 0.1"`
+
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+     HAVE_STEREOPIXEL="yes"
+  else
+     HAVE_STEREOPIXEL="no"
+  fi
+
+if test "x$HAVE_STEREOPIXEL" = "xyes"; then
+    { echo "$as_me:$LINENO: Set STEREOPIXEL_CPPFLAGS... $STEREOPIXEL_CPPFLAGS" >&5
+echo "$as_me: Set STEREOPIXEL_CPPFLAGS... $STEREOPIXEL_CPPFLAGS" >&6;}
+
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STEREOPIXEL 1
+_ACEOF
+
+    AVAIL_EXTLIBS="stereopixel $AVAIL_EXTLIBS"
 fi
 
 ## check for boost-sandbox ##
@@ -25365,6 +25480,9 @@ QT4_LDFLAGS!$QT4_LDFLAGS$ac_delim
 CALIFECAMERA_CPPFLAGS!$CALIFECAMERA_CPPFLAGS$ac_delim
 CALIFECAMERA_LIBS!$CALIFECAMERA_LIBS$ac_delim
 CALIFECAMERA_LDFLAGS!$CALIFECAMERA_LDFLAGS$ac_delim
+STEREOPIXEL_CPPFLAGS!$STEREOPIXEL_CPPFLAGS$ac_delim
+STEREOPIXEL_LIBS!$STEREOPIXEL_LIBS$ac_delim
+STEREOPIXEL_LDFLAGS!$STEREOPIXEL_LDFLAGS$ac_delim
 BOOST_SANDBOX_CPPFLAGS!$BOOST_SANDBOX_CPPFLAGS$ac_delim
 LAPACK_LDFLAGS!$LAPACK_LDFLAGS$ac_delim
 LAPACK_LIBS!$LAPACK_LIBS$ac_delim
@@ -25385,7 +25503,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 32; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 35; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
