Add checking for Accelerate Framework in order to use lapack on Macos X
git-svn-id: svn+ssh://svn.laas.fr/svn/jafar/jafarBackbone/trunk@1639 d3dd4ecc-a6df-0310-ac42-d4bc92953605

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1106,6 +1106,21 @@ Optional Packages:
       alternatively, you can specify:
         --with-lapacklib=dir : the lapack package's lib directory
 
+  --with-accelerate
+  --with-accelerate=dir
+  --without-accelerate
+
+  --with-accelerateinc=dir
+      support for LAPACK through Accelerate Framework (only available on MacOSX). default: --with-accelerate
+      if --with-accelerate or --with-accelerate=yes is given: accelerate package files will be
+         searched for in some standard directories (the default).
+      if --with-accelerate=dir is given, and dir is a directory: accelerate package files
+         will be searched for below 'dir' using 'find'.
+      if --with-accelerate=no or --without-accelerate is given: accelerate package will
+         not be used.
+      alternatively, you can specify:
+        --with-accelerateinc=dir : the accelerate package's include directory
+
   --with-opengl
   --with-opengl=dir
   --without-opengl
@@ -3735,7 +3750,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3738 "configure"' > conftest.$ac_ext
+  echo '#line 3753 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4843,7 +4858,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4846:" \
+echo "$as_me:4861:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5873,11 +5888,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5876: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5891: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5880: \$? = $ac_status" >&5
+   echo "$as_me:5895: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6105,11 +6120,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6108: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6123: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6112: \$? = $ac_status" >&5
+   echo "$as_me:6127: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6172,11 +6187,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6175: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6190: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6179: \$? = $ac_status" >&5
+   echo "$as_me:6194: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8304,7 +8319,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8307 "configure"
+#line 8322 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8402,7 +8417,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8405 "configure"
+#line 8420 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10585,11 +10600,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10588: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10603: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10592: \$? = $ac_status" >&5
+   echo "$as_me:10607: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10652,11 +10667,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10655: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10670: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10659: \$? = $ac_status" >&5
+   echo "$as_me:10674: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11981,7 +11996,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11984 "configure"
+#line 11999 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12079,7 +12094,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12082 "configure"
+#line 12097 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12904,11 +12919,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12907: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12922: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12911: \$? = $ac_status" >&5
+   echo "$as_me:12926: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12971,11 +12986,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12974: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12989: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12978: \$? = $ac_status" >&5
+   echo "$as_me:12993: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14950,11 +14965,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14953: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14968: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14957: \$? = $ac_status" >&5
+   echo "$as_me:14972: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15182,11 +15197,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15185: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15200: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15189: \$? = $ac_status" >&5
+   echo "$as_me:15204: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15249,11 +15264,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15252: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15267: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15256: \$? = $ac_status" >&5
+   echo "$as_me:15271: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17381,7 +17396,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17384 "configure"
+#line 17399 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17479,7 +17494,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17482 "configure"
+#line 17497 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20450,6 +20465,181 @@ echo "$as_me: WARNING: Configuring without lapack support " >&2;}
     fi
 
 
+
+
+# Check whether --with-accelerate or --without-accelerate was given.
+if test "${with_accelerate+set}" = set; then
+  withval="$with_accelerate"
+
+fi;
+
+
+# Check whether --with-accelerateinc or --without-accelerateinc was given.
+if test "${with_accelerateinc+set}" = set; then
+  withval="$with_accelerateinc"
+
+fi;
+
+
+    # default is "no"
+    if test ${with_accelerate:-""} = ""; then
+        with_accelerate="no"
+    fi
+
+    if test ${with_accelerate:-""} != "no"; then
+	found_accelerate="yes"
+
+
+    if test "Accelerate/Accelerate.h" != ""; then
+        echo "$as_me:$LINENO: checking for Accelerate/Accelerate.h " >&5
+echo $ECHO_N "checking for Accelerate/Accelerate.h ... $ECHO_C" >&6
+
+        # check whether the include is in the path by default (e.g. /usr/include)
+        include_found=""
+        if test "$with_accelerateinc" = "" -a "$with_accelerate" = "yes"; then
+            cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdio.h>  /* necessary because jpeglib.h fails to include it */
+#include <Accelerate/Accelerate.h>
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  include_found="in default path"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+include_found=""
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+        fi
+
+        # if not found by default, try searching for it
+        if test "$include_found" = ""; then
+            dirs=""
+            if test "$with_accelerateinc" != ""; then
+                dirs="$with_accelerateinc"
+            elif test "$with_accelerate" != "yes"; then
+                dirs="$with_accelerate"
+            else
+                dirs="/usr/local/include /usr/local/gnu/include /usr/local/accelerate /usr/local/accelerate/include /opt/include /opt/gnu/include /opt/accelerate /opt/accelerate/include /opt/local/include /opt/local/include/accelerate /usr/include /sw /sw/include /sw/accelerate /sw/accelerate/include \$HOME/ \$HOME/include \$HOME/usr \$HOME/usr/include \$HOME/usr/accelerate \$HOME/opt \$HOME/opt/include \$HOME/opt/accelerate \$HOME/accelerate \$HOME/local \$HOME/local/include \$HOME/local/accelerate"
+            fi
+
+            # use find for searching
+
+    if test "$findprog" = ""; then
+        if test "$CYGWIN" = "yes"; then
+          findprog="/usr/bin/find"
+        else
+          findprog="find"
+        fi
+    fi
+
+
+            # first, look for the given header file without directory components..
+            found=""
+            for i in $dirs; do
+                if test -d $i; then
+                    found="$found `$findprog $i -follow -name Accelerate.h -print 2> /dev/null`"
+                fi
+            done
+
+            # now, check each found file for relative path prefix.
+
+    regExResult=""
+    if test "$found" != ""; then
+        for i in $found; do
+            regExResult=`expr "$i" : "\(.*include\)/Accelerate/Accelerate\.h"`
+            if test "$regExResult" != ""; then
+                break
+            fi
+        done
+    fi
+
+            if test "$regExResult" = ""; then
+
+    regExResult=""
+    if test "$found" != ""; then
+        for i in $found; do
+            regExResult=`expr "$i" : "\(.*\)/Accelerate/Accelerate\.h"`
+            if test "$regExResult" != ""; then
+                break
+            fi
+        done
+    fi
+
+            fi
+            include_found=$regExResult
+        fi
+
+        # report the search result and set result variables
+        if test "$include_found" = ""; then
+            with_accelerateinc=""
+            echo "$as_me:$LINENO: result: not found in $dirs" >&5
+echo "${ECHO_T}not found in $dirs" >&6
+        else
+            echo "$as_me:$LINENO: result: $include_found" >&5
+echo "${ECHO_T}$include_found" >&6
+            if test "$include_found" != "/usr/include" -a \
+                    "$include_found" != "in default path"; then
+                with_accelerateinc="$include_found"
+                accelerate_cppflags="-I$include_found"
+            else
+                with_accelerateinc=""
+                accelerate_cppflags=""
+            fi
+        fi
+    else
+        with_accelerateinc=""
+        accelerate_cppflags=""
+    fi
+
+	 	if test "x$include_found" = "x"; then
+			found_accelerate="no"
+        	fi
+
+
+
+	with_accelerate="yes";
+    else
+	with_accelerate="no"
+	{ echo "$as_me:$LINENO: WARNING: Configuring without accelerate support " >&5
+echo "$as_me: WARNING: Configuring without accelerate support " >&2;}
+    fi
+
+
 if test "x$with_lapack" = "xyes";
 then
     LAPACK_LDFLAGS="$with_lapacklib"
@@ -20463,6 +20653,20 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+if test "x$with_accelerate" = "xyes";
+then
+    LAPACK_LIBS="-Wl,-framework -Wl,Accelerate"
+    LAPACK_LDFLAGS="-faltivec"
+    AVAIL_EXTLIBS="lapack $AVAIL_EXTLIBS"
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LAPACK 1
+_ACEOF
+
+fi
+
 
 ## check for openGL ##
 
